export const data = {
  products: [
    {
      id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/product1.webp",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      id: 2,
      name: "Addidas Fit Shirt",
      category: "Shirts",
      image: "/images/product7.webp",
      price: 110,
      brand: "Addidas",
      rating: 4.6,
      numReviews: 7,
      description: "High quality product",
    },
    {
      id: 3,
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/product8.webp",
      price: 150,
      brand: "Lacoste",
      rating: 4.9,
      numReviews: 19,
      description: "High quality product",
    },
    {
      id: 4,
      name: "Nike Sweat pant",
      category: "Pant",
      image: "/images/product4.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.7,
      numReviews: 20,
      description: "High quality pant",
    },
    {
      id: 5,
      name: "Addidas Gym Shoe",
      category: "Shoe",
      image: "/images/product8.webp",
      price: 120,
      brand: "Addidas",
      rating: 4.6,
      numReviews: 5,
      description: "High quality product",
    },
    {
      id: 6,
      name: "Nike Running Shoe",
      category: "Shoe",
      image: "/images/product7.webp",
      price: 180,
      brand: "Nike",
      rating: 5,
      numReviews: 28,
      description: "High quality product",
    },
  ],
};
